// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bBMnSDTUpYxJArndSZP39h
// Component: 7KKl0p7S05TKo1
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: GN7B5DqBtJ2dm8/component
import Section from "../../Section"; // plasmic-import: eA2_yOcj5Z_8HX/component
import Teams from "../../Teams"; // plasmic-import: 7dv2xhJxLvdWRh/component
import TextInput from "../../TextInput"; // plasmic-import: SlEtZvoCOog5nH/component
import Button from "../../Button"; // plasmic-import: KMBJmHNsD0xfZo/component
import FooterSection from "../../FooterSection"; // plasmic-import: nYxyEfIdx2-Y7e/component
import { useScreenVariants as useScreenVariantsxXlfASnpAjvg2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: x_xlfASnpAjvg2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_light_saa_s_landing_page.module.css"; // plasmic-import: bBMnSDTUpYxJArndSZP39h/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 7KKl0p7S05TKo1/css
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: oMoeU_rIsegp/icon
import pet12843071920JpgUhYdkQfNd from "./images/pet12843071920Jpg.jpeg"; // plasmic-import: UhYDKQfND/picture
import dogs44295131920Jpg4GvGEdo62 from "./images/dogs44295131920Jpg.jpeg"; // plasmic-import: 4gvGEdo62/picture
import banksvgIQyGgx4M3DvEp from "./images/banksvg.svg"; // plasmic-import: iQYGgx4m3Dv_ep/picture
import lineBluesvg3CrCbzNPeQzp from "./images/lineBluesvg.svg"; // plasmic-import: 3crCbz_nPEQzp_/picture
import puppy51249481920JpgFvFGcbH2O from "./images/puppy51249481920Jpg.jpeg"; // plasmic-import: fvFGcbH2O/picture
import fattyCorgiZn5ChZcnFraUnsplashjpgBzr6Kr2Rs from "./images/fattyCorgiZn5ChZcnFraUnsplashjpg.jpeg"; // plasmic-import: Bzr6kr2Rs/picture
import tickCirclesvgT9UkJ4AL6THaKh from "./images/tickCirclesvg.svg"; // plasmic-import: T9UkJ4aL6tHaKH/picture
import karstenWinegeartOU6KztXhuvkUnsplashjpgWDtnAeOXn from "./images/karstenWinegeartOU6KztXhuvkUnsplashjpg.jpeg"; // plasmic-import: wDtnAeOXn/picture
import heroImgpngBkIkYjrg5WJ3H from "./images/heroImgpng.png"; // plasmic-import: Bk_ikYJRG5wJ3H/picture
import minusCirlcesvgA7GdLV5RQsZ9 from "./images/minusCirlcesvg.svg"; // plasmic-import: a7GdL-V5RQs_z9/picture
import addCirclesvgGtlR7XIyoX8Lks from "./images/addCirclesvg.svg"; // plasmic-import: gtlR7xIyoX8lks/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxXlfASnpAjvg2()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"headerHeroSection"}
              data-plasmic-override={overrides.headerHeroSection}
              hasGap={true}
              className={classNames(projectcss.all, sty.headerHeroSection)}
            >
              {true ? (
                <Navbar
                  data-plasmic-name={"navbar"}
                  data-plasmic-override={overrides.navbar}
                  className={classNames("__wab_instance", sty.navbar)}
                />
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__p0JaA)}>
                <div className={classNames(projectcss.all, sty.freeBox__e1Rk)}>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__ftEmc
                    )}
                  >
                    {"Training Dogs The Fun And Effective Way"}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bFezr
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </div>
                </div>
              </div>
            </p.Stack>
          ) : null}

          <Section
            className={classNames("__wab_instance", sty.section__ting6)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ruo6E)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"1140px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"1164px"}
              loading={"lazy"}
              src={{
                src: pet12843071920JpgUhYdkQfNd,
                fullWidth: 1920,
                fullHeight: 1248,
                aspectRatio: undefined
              }}
            />
          </Section>

          <Section
            className={classNames("__wab_instance", sty.section__sFHu)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__kc77)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__tF228
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Lorem Ipsum"
                  : "Lorem Ipsum"}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__z543
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
                }
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__kzaGi)}>
                <div className={classNames(projectcss.all, sty.columns__eIjJf)}>
                  <div
                    className={classNames(projectcss.all, sty.column__xfjHr)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__cqz5R
                      )}
                    >
                      {"15 +"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6OKCk
                      )}
                    >
                      {"Years Expireance"}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___0Hk9Y)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___8S0Bj
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "5,2X"
                        : "1259 +"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ohC4K
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Average traffic increase"
                        : "Dog Trained"}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__hMtRt)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__qrP6M
                      )}
                    >
                      {"12"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hoJy5
                      )}
                    >
                      {"In-House Trainers"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Section>

          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(projectcss.all, sty.section__s2Iko)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground"}
              data-plasmic-override={overrides.foreground}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__hNkuC)}
              >
                <div className={classNames(projectcss.all, sty.column__h0H0P)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lXSfr)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4Zlk3
                      )}
                    >
                      {"Training"}
                    </div>

                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__eme7O
                      )}
                    >
                      {"Effective dog training, real behavior solutions"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qX2AJ
                      )}
                    >
                      {
                        "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                      }
                    </div>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__qxPos)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xLxi3)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0YaYk
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1TYee
                        )}
                      >
                        {"Develop a clear and loving relationship"}
                      </div>

                      <Icon16Icon
                        className={classNames(projectcss.all, sty.svg__qdPow)}
                        role={"img"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__n7IPw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eEyMn
                        )}
                      >
                        {"Being able to communicate with them"}
                      </div>

                      <Icon16Icon
                        className={classNames(projectcss.all, sty.svg___0E5CE)}
                        role={"img"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__dssa7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ruwV3
                        )}
                      >
                        {"Always be eager to please"}
                      </div>

                      <Icon16Icon
                        className={classNames(projectcss.all, sty.svg__ikgcL)}
                        role={"img"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__bw9Vv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__blwNc
                        )}
                      >
                        {"Create a golden relationship"}
                      </div>

                      <Icon16Icon
                        className={classNames(projectcss.all, sty.svg__c5OeM)}
                        role={"img"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__wyhdj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cvoEa
                        )}
                      >
                        {"Best results"}
                      </div>

                      <Icon16Icon
                        className={classNames(projectcss.all, sty.svg__qjU2A)}
                        role={"img"}
                      />
                    </p.Stack>
                  </div>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Section
            className={classNames("__wab_instance", sty.section__q67Fx)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__sJnJb)}>
              <div className={classNames(projectcss.all, sty.columns__th7HZ)}>
                <div className={classNames(projectcss.all, sty.column___0MaFv)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__btUj0)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"500px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "auto"
                    }
                    loading={"lazy"}
                    src={{
                      src: dogs44295131920Jpg4GvGEdo62,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___8ElIc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bQli8)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__kmjMh)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: banksvgIQyGgx4M3DvEp,
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0P2Z
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                        }
                      </div>
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column___7MmvR)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nNpsg)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__laiDw)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___93Nd)}
                        displayHeight={"2px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"26px"}
                        loading={"lazy"}
                        src={{
                          src: lineBluesvg3CrCbzNPeQzp,
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pki8Z
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>

                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__ee2Zn
                      )}
                    >
                      {"Lorem Ipsum"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__luWOy
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. "
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__oW6Hb)}>
              <div className={classNames(projectcss.all, sty.columns___9LwSt)}>
                <div className={classNames(projectcss.all, sty.column___3Wz9Y)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__b26VM)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ywv4C)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___9V7Zz)}
                        displayHeight={"2px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"26px"}
                        loading={"lazy"}
                        src={{
                          src: lineBluesvg3CrCbzNPeQzp,
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kItm0
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>

                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__dsWo7
                      )}
                    >
                      {"Lorem Ipsum"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7Hdn6
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. "
                      }
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__jAxjN)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___9SHVh)}
                    displayHeight={"350px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "689px"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: puppy51249481920JpgFvFGcbH2O,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__nXsw)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tGuz6)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__j8E1Y)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: banksvgIQyGgx4M3DvEp,
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7WqY
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                        }
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__la577)}>
              <div className={classNames(projectcss.all, sty.columns__aqqCe)}>
                <div className={classNames(projectcss.all, sty.column___0Fd2C)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__a4F0)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "500px"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: fattyCorgiZn5ChZcnFraUnsplashjpgBzr6Kr2Rs,
                      fullWidth: 1920,
                      fullHeight: 1281,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__sFvBe)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qApmi)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__du6FD)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: banksvgIQyGgx4M3DvEp,
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w0Obi
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                        }
                      </div>
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__jIp3X)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nzYdb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qEcnn)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mzJwm)}
                        displayHeight={"2px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"26px"}
                        loading={"lazy"}
                        src={{
                          src: lineBluesvg3CrCbzNPeQzp,
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vXvP8
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>

                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___0YRcx
                      )}
                    >
                      {"Lorem Ipsum"}
                    </h3>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__laq0O
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. "
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Section>

          <Section
            background={"darkBlue"}
            className={classNames("__wab_instance", sty.section___46PZb)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__iKrin)}>
              <div className={classNames(projectcss.all, sty.freeBox___1TmIo)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__wBsBp
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem Ipsum"
                    : "Lorem Ipsum"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___62Kno
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."}
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__p8IzP)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jXa18)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__mdPfb)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: tickCirclesvgT9UkJ4AL6THaKh,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__c9MVz)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cvmAh
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__i4NV)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jdrpo)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rSXh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: tickCirclesvgT9UkJ4AL6THaKh,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__vKl4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oHeoW
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__aHibe)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vsEdj)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xFmeX)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: tickCirclesvgT9UkJ4AL6THaKh,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__wY1Qk)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xZ2Dr
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>

                <div
                  className={classNames(projectcss.all, sty.freeBox___2FDyi)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__uXb9O)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__t2E1S)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: tickCirclesvgT9UkJ4AL6THaKh,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__rx7Dv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__htFtu
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__r9OXr)}>
                {(
                  hasVariant(globalVariants, "screen", "mobile") ? true : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__faMn5)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "700px"
                    }
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "174px"
                        : "none"
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "1440px"
                    }
                    loading={"lazy"}
                    src={{
                      src: karstenWinegeartOU6KztXhuvkUnsplashjpgWDtnAeOXn,
                      fullWidth: 2688,
                      fullHeight: 3360,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobile") ? true : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qDocW)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: heroImgpngBkIkYjrg5WJ3H,
                      fullWidth: 2280,
                      fullHeight: 1400,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
              </div>
            </div>
          </Section>

          <Section
            className={classNames("__wab_instance", sty.section__ch3Pr)}
            size={"fullContentWidth"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ej3N)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__vmCk
                )}
              >
                {"Lorem Ipsum"}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jwCtP
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."}
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__e1TYg)}
              >
                <Teams
                  className={classNames("__wab_instance", sty.teams__eeU9C)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__rInbv)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__nyev7)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__q9XCn)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__gxWbd)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__rJrKx)}
                />
              </p.Stack>
            </div>
          </Section>

          <Section
            background={"blue"}
            className={classNames("__wab_instance", sty.section__l6Kw)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          />

          <Section
            className={classNames("__wab_instance", sty.section__iyuvt)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "faq"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__cdgD)}>
              <div className={classNames(projectcss.all, sty.freeBox___2KgR2)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q2It
                  )}
                >
                  {"FAQ"}
                </div>

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___8SCm
                  )}
                >
                  {"Lorem Ipsum"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6ZfSq
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
                  }
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__l6PuL)}>
                <div className={classNames(projectcss.all, sty.freeBox__khNIs)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ltrHk)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__ojBbG
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__jKsd9)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: minusCirlcesvgA7GdLV5RQsZ9,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x6Cs
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
                    }
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__xZhLy)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eXxCz)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__tA4DX
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__oJvM)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: addCirclesvgGtlR7XIyoX8Lks,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__xgdre)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iyIdf)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__yGQyp
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___2Ngoq)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: addCirclesvgGtlR7XIyoX8Lks,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__oCzn)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ddlHl)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__ogTqd
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__txWkb)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: addCirclesvgGtlR7XIyoX8Lks,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__ucJoj)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fuRrq)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__wjtan
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xlOoR)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: addCirclesvgGtlR7XIyoX8Lks,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </Section>

          <Section
            background={"blue"}
            className={classNames("__wab_instance", sty.section__k4ZnA)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__t1COy)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__pjYbF
                )}
              >
                {"Lorem Ipsum"}
              </h1>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rKb8
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                }
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wwb0C)}
              >
                <TextInput
                  data-plasmic-name={"textInput"}
                  data-plasmic-override={overrides.textInput}
                  className={classNames("__wab_instance", sty.textInput)}
                />

                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  color={"blue"}
                  link={"#"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iawbu
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Subscribe"
                      : "Subscribe"}
                  </div>
                </Button>
              </p.Stack>
            </div>
          </Section>

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "foreground",
    "textInput",
    "textbox",
    "button",
    "footerSection"
  ],

  headerHeroSection: ["headerHeroSection", "navbar"],
  navbar: ["navbar"],
  foreground: ["foreground"],
  textInput: ["textInput", "textbox"],
  button: ["button"],
  footerSection: ["footerSection"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    foreground: makeNodeComponent("foreground"),
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    footerSection: makeNodeComponent("footerSection"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
