// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bBMnSDTUpYxJArndSZP39h
import * as React from "react";
import { WordpressProvider } from "@plasmicpkgs/plasmic-wordpress"; // plasmic-import: ABVULPU3AuC/codeComponent

export default function GlobalContextsProvider(props) {
  const { children, wordpressProviderProps } = props;
  return (
    <WordpressProvider
      {...wordpressProviderProps}
      wordpressUrl={
        wordpressProviderProps && "wordpressUrl" in wordpressProviderProps
          ? wordpressProviderProps.wordpressUrl
          : "https://techcrunch.com/"
      }
    >
      {children}
    </WordpressProvider>
  );
}
